spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  main:
    allow-circular-references: true

